"""
Step 6 — Insurance Report (F6)
Auto-generates a PDF incident report after each accident.
"""

from fpdf import FPDF
import os
from datetime import datetime


def generate_report(event: dict, clip_path: str, output_dir: str = "reports/") -> str:
    """
    Generates a PDF incident report.

    Args:
        event: dict with keys: timestamp, camera_id, gps, severity, vehicles, confidence,
               severity_breakdown (optional)
        clip_path: path to the blackbox MP4 clip
        output_dir: directory to save reports

    Returns:
        path to the saved PDF file
    """
    os.makedirs(output_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = os.path.join(output_dir, f"incident_{timestamp}.pdf")

    pdf = FPDF()
    pdf.add_page()

    # ── Header ──────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 22)
    pdf.cell(0, 15, "AegisEye Incident Report", ln=True, align="C")
    pdf.ln(5)

    # ── Divider line ────────────────────────────────────
    pdf.set_draw_color(200, 0, 0)
    pdf.set_line_width(0.8)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(10)

    # ── Details ─────────────────────────────────────────
    details = [
        ("Date / Time", event.get("timestamp", "N/A")),
        ("Camera ID", event.get("camera_id", "N/A")),
        ("GPS Location", f"{event['gps']['lat']}, {event['gps']['lng']}"),
        ("Severity", event.get("severity", "N/A")),
        ("Vehicles Involved", ", ".join(event.get("vehicles", [])) or "None detected"),
        ("Detection Confidence", f"{event.get('confidence', 0):.0%}"),
    ]

    for label, value in details:
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(60, 10, f"{label}:")
        pdf.set_font("Helvetica", "", 12)
        pdf.cell(0, 10, str(value), ln=True)

    # ── Blackbox clip as clickable link ─────────────────
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(60, 10, "Blackbox Clip:")
    if clip_path and os.path.exists(clip_path):
        clip_display = os.path.basename(clip_path)
        abs_clip = os.path.abspath(clip_path).replace("\\", "/")
        file_uri = f"file:///{abs_clip}"
        pdf.set_font("Helvetica", "U", 12)
        pdf.set_text_color(30, 100, 220)
        pdf.cell(0, 10, clip_display, ln=True, link=file_uri)
        pdf.set_text_color(0, 0, 0)
    else:
        pdf.set_font("Helvetica", "", 12)
        pdf.cell(0, 10, "N/A", ln=True)

    # ── Severity Breakdown ──────────────────────────────
    breakdown = event.get("severity_breakdown")
    if breakdown:
        pdf.ln(8)
        pdf.set_draw_color(100, 100, 100)
        pdf.set_line_width(0.3)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(5)

        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 10, "Severity Breakdown", ln=True)
        pdf.ln(2)

        components = [
            ("Motion Spike", breakdown.get("motion_spike", 0), 0.40),
            ("Accident Confidence", breakdown.get("accident_confidence", 0), 0.30),
            ("Motion Magnitude", breakdown.get("motion_magnitude", 0), 0.20),
            ("Vehicle Bonus", breakdown.get("vehicle_bonus", 0), 0.10),
        ]

        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(70, 8, "Component")
        pdf.cell(30, 8, "Score", align="C")
        pdf.cell(30, 8, "Weight", align="C")
        pdf.cell(30, 8, "Weighted", align="C")
        pdf.ln()

        pdf.set_draw_color(180, 180, 180)
        pdf.line(10, pdf.get_y(), 170, pdf.get_y())
        pdf.ln(1)

        pdf.set_font("Helvetica", "", 10)
        for name, score, weight in components:
            weighted = score * weight
            pdf.cell(70, 7, name)
            pdf.cell(30, 7, f"{score:.3f}", align="C")
            pdf.cell(30, 7, f"{weight:.0%}", align="C")
            pdf.cell(30, 7, f"{weighted:.3f}", align="C")
            pdf.ln()

        pdf.ln(2)
        pdf.set_font("Helvetica", "B", 11)
        total = breakdown.get("weighted_score", 0)
        pdf.cell(70, 8, "Total Score:")
        pdf.cell(30, 8, "")
        pdf.cell(30, 8, "")
        pdf.cell(30, 8, f"{total:.3f}", align="C")
        pdf.ln()

    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 10)
    pdf.cell(0, 10, "This report was auto-generated by AegisEye.", ln=True, align="C")

    pdf.output(filename)
    return filename
