


"""
Step 5 — Emergency Alert (F5)
Sends formatted Email alert with PDF report and blackbox clip.
"""

import smtplib
import os
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication

GMAIL_USER = "danipromax345@gmail.com"
GMAIL_APP_PASSWORD = "jlsv wxde muzl gmjx"
ALERT_TO = "danipromax345@gmail.com"
ALERT_ENABLED = True


def send_alert(event: dict, pdf_path: str = None, clip_path: str = None) -> str:
    if not ALERT_ENABLED:
        print(f"[ALERT] (disabled) Would send: "
              f"Severity={event['severity']}, "
              f"Vehicles={event['vehicles']}, "
              f"GPS={event['gps']}")
        return "disabled"

    severity = event['severity']
    vehicles = ', '.join(event['vehicles'])
    lat = event['gps']['lat']
    lng = event['gps']['lng']
    maps_url = event.get('maps_url', f"https://maps.google.com/?q={lat},{lng}")
    timestamp = event['timestamp']

    color = {"High": "#e74c3c", "Medium": "#f39c12", "Low": "#27ae60"}.get(severity, "#333")

    html = f"""
    <div style="font-family: Arial, sans-serif; max-width: 500px; border: 2px solid {color}; border-radius: 8px; overflow: hidden;">
        <div style="background: {color}; color: white; padding: 14px 20px;">
            <h2 style="margin: 0;">AegisEye — Accident Alert</h2>
        </div>
        <div style="padding: 20px;">
            <table style="width: 100%; border-collapse: collapse;">
                <tr><td style="padding: 8px 0; color: #666;"><b>Severity</b></td>
                    <td style="padding: 8px 0;"><b style="color: {color};">{severity}</b></td></tr>
                <tr><td style="padding: 8px 0; color: #666;"><b>Vehicles</b></td>
                    <td style="padding: 8px 0;">{vehicles}</td></tr>
                <tr><td style="padding: 8px 0; color: #666;"><b>Location</b></td>
                    <td style="padding: 8px 0;">{lat}, {lng}</td></tr>
                <tr><td style="padding: 8px 0; color: #666;"><b>Camera</b></td>
                    <td style="padding: 8px 0;">{event.get('camera_name', 'Unknown')}</td></tr>
                <tr><td style="padding: 8px 0; color: #666;"><b>Time</b></td>
                    <td style="padding: 8px 0;">{timestamp}</td></tr>
            </table>
            <a href="{maps_url}" style="display: inline-block; margin-top: 14px; padding: 10px 20px;
               background: {color}; color: white; text-decoration: none; border-radius: 5px;
               font-weight: bold;">View on Google Maps</a>
            <p style="margin-top: 16px; color: #333;"><b>Respond immediately.</b></p>
        </div>
        <div style="background: #f5f5f5; padding: 12px 20px; border-top: 1px solid #ddd;">
            <p style="margin: 0; font-size: 12px; color: #999; text-align: center;">
                Automated alert generated by <b>AegisEye</b> — Real-Time Accident Detection System<br>
            </p>
        </div>
    </div>
    """

    msg = MIMEMultipart()
    msg["Subject"] = f"ACCIDENT ALERT — {severity} Severity"
    msg["From"] = GMAIL_USER
    msg["To"] = ALERT_TO
    msg.attach(MIMEText(html, "html"))

    if pdf_path and os.path.exists(pdf_path):
        with open(pdf_path, "rb") as f:
            pdf = MIMEApplication(f.read(), _subtype="pdf")
            pdf.add_header("Content-Disposition", "attachment",
                           filename=os.path.basename(pdf_path))
            msg.attach(pdf)

    if clip_path and os.path.exists(clip_path):
        with open(clip_path, "rb") as f:
            clip = MIMEApplication(f.read(), _subtype="mp4")
            clip.add_header("Content-Disposition", "attachment",
                           filename=os.path.basename(clip_path))
            msg.attach(clip)

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(GMAIL_USER, GMAIL_APP_PASSWORD)
            server.send_message(msg)
        print("[ALERT] Email sent!")
        return "sent"
    except Exception as e:
        print(f"[ALERT] Email failed: {e}")
        return f"error: {e}"








# """
# Step 5 — Emergency Alert (F5)
# Sends Email alert when accident detected.
# """

# import smtplib
# from email.mime.text import MIMEText

# GMAIL_USER = "danipromax345@gmail.com"
# GMAIL_APP_PASSWORD = "jlsv wxde muzl gmjx"
# ALERT_TO = "danipromax345@gmail.com,70150006@student.uol.edu.pk"  # or any recipient
# ALERT_ENABLED = True


# def send_alert(event: dict) -> str:
#     if not ALERT_ENABLED:
#         print(f"[ALERT] (disabled) Would send: "
#               f"Severity={event['severity']}, "
#               f"Vehicles={event['vehicles']}, "
#               f"GPS={event['gps']}")
#         return "disabled"

#     body = (
#         f"AEGISEYE ACCIDENT ALERT\n\n"
#         f"Severity: {event['severity']}\n"
#         f"Vehicles: {', '.join(event['vehicles'])}\n"
#         f"Location: {event['gps']['lat']}, {event['gps']['lng']}\n"
#         f"Maps: https://maps.google.com/?q={event['gps']['lat']},{event['gps']['lng']}\n"
#         f"Time: {event['timestamp']}\n\n"
#         f"Respond immediately."
#     )

#     msg = MIMEText(body)
#     msg["Subject"] = f"ACCIDENT ALERT - {event['severity']} Severity"
#     msg["From"] = GMAIL_USER
#     msg["To"] = ALERT_TO

#     try:
#         with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
#             server.login(GMAIL_USER, GMAIL_APP_PASSWORD)
#             server.send_message(msg)
#         print("[ALERT] Email sent!")
#         return "sent"
#     except Exception as e:
#         print(f"[ALERT] Email failed: {e}")
#         return f"error: {e}"







# """
# Step 5 — Emergency Alert (F5)
# Sends Telegram alert when accident detected.
# """

# import requests

# BOT_TOKEN = "paste_bot_token_here"
# CHAT_ID = "paste_chat_id_here"
# ALERT_ENABLED = True


# def send_alert(event: dict) -> str:
#     if not ALERT_ENABLED:
#         print(f"[ALERT] (disabled) Would send: "
#               f"Severity={event['severity']}, "
#               f"Vehicles={event['vehicles']}, "
#               f"GPS={event['gps']}")
#         return "disabled"

#     message = (
#         f"🚨 AEGISEYE ACCIDENT ALERT\n\n"
#         f"Severity: {event['severity']}\n"
#         f"Vehicles: {', '.join(event['vehicles'])}\n"
#         f"📍 Location: {event['gps']['lat']}, {event['gps']['lng']}\n"
#         f"🗺 https://maps.google.com/?q={event['gps']['lat']},{event['gps']['lng']}\n"
#         f"🕐 Time: {event['timestamp']}\n\n"
#         f"Respond immediately."
#     )

#     try:
#         response = requests.get(f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage", params={
#             "chat_id": CHAT_ID,
#             "text": message,
#         })
#         data = response.json()
#         if data.get("ok"):
#             print(f"[ALERT] Telegram sent!")
#             return "sent"
#         else:
#             print(f"[ALERT] Telegram error: {data}")
#             return f"error: {data}"
#     except Exception as e:
#         print(f"[ALERT] Telegram failed: {e}")
#         return f"error: {e}"








# """
# Step 5 — Emergency Alert (F5)
# Sends SMS via Twilio when accident detected.
# """

# from twilio.rest import Client
# import config

# TWILIO_ENABLED = True


# def send_alert(event: dict) -> str:
#     if not TWILIO_ENABLED:
#         print(f"[ALERT] (SMS disabled) Would send: "
#               f"Severity={event['severity']}, "
#               f"Vehicles={event['vehicles']}, "
#               f"GPS={event['gps']}")
#         return "disabled"

#     message_body = (
#         f"AEGISEYE ACCIDENT ALERT\n\n"
#         f"Severity: {event['severity']}\n"
#         f"Vehicles: {', '.join(event['vehicles'])}\n"
#         f"Location: {event['gps']['lat']}, {event['gps']['lng']}\n"
#         f"Maps: https://maps.google.com/?q={event['gps']['lat']},{event['gps']['lng']}\n"
#         f"Time: {event['timestamp']}\n\n"
#         f"Respond immediately."
#     )

#     try:
#         client = Client(config.TWILIO_SID, config.TWILIO_TOKEN)
#         msg = client.messages.create(
#             body=message_body,
#             messaging_service_sid="MG11ec6eb7e65ee8fb82cd7d71595b2995",
#             to=config.EMERGENCY_TO,
#         )
#         print(f"[ALERT] SMS sent! SID: {msg.sid}")
#         return msg.sid
#     except Exception as e:
#         print(f"[ALERT] SMS failed: {e}")
#         return f"error: {e}"



# """
# Step 5 — Emergency Alert (F5)
# Sends SMS via SendPK API when accident detected.
# """

# import requests

# SENDPK_API_KEY = "923288104765-65797e42-37f7-49ae-986b-9a770e7211a6"
# EMERGENCY_TO = "923467665411"
# SMS_ENABLED = True


# def send_alert(event: dict) -> str:
#     if not SMS_ENABLED:
#         print(f"[ALERT] (SMS disabled) Would send: "
#               f"Severity={event['severity']}, "
#               f"Vehicles={event['vehicles']}, "
#               f"GPS={event['gps']}")
#         return "disabled"

#     message = (
#         f"AEGISEYE ACCIDENT ALERT\n\n"
#         f"Severity: {event['severity']}\n"
#         f"Vehicles: {', '.join(event['vehicles'])}\n"
#         f"Location: {event['gps']['lat']}, {event['gps']['lng']}\n"
#         f"Maps: https://maps.google.com/?q={event['gps']['lat']},{event['gps']['lng']}\n"
#         f"Time: {event['timestamp']}\n\n"
#         f"Respond immediately."
#     )

#     try:
#         response = requests.get("https://sendpk.com/api/sms.php", params={
#             "api_key": SENDPK_API_KEY,
#             "sender":  "AegisEye",
#             "mobile":  EMERGENCY_TO,
#             "message": message,
#         })
#         print(f"[ALERT] SendPK response: {response.text}")
#         return response.text
#     except Exception as e:
#         print(f"[ALERT] SMS failed: {e}")
#         return f"error: {e}"